namespace Neti.CodeGenerator
{
	public static class CodeConstants
	{
		public static readonly string MessageCodeIndent = "			";
		public static readonly string AutoGeneratedHeader =
@"//-------------------------------------------------------
//
// Auto Generated Code. Do NOT edit this.
//
//-------------------------------------------------------";
	}
}
