namespace Neti.CodeGenerator
{
	public static class Global
	{
		public static readonly string AutoGeneratedHeader =
@"//-------------------------------------------------------
//
// Auto Generated Code. Do NOT edit this.
//
//-------------------------------------------------------";
	}
}
