using System;
using System.Linq;
using System.Reflection;

namespace Neti.CodeGeneration
{
	public static class CodeGenerationUtility
	{
		public static readonly string MessageGroupIndent = "			";

		public static string BuildMessageGroupCode(string usingCode,
												   string namespaceName,
												   string messageGroupName,
												   string internalClassName,
												   string internalClassCode)
		{
			var code =
$@"{CodeConstants.AutoGeneratedHeader}

{(string.IsNullOrEmpty(usingCode) ? "// No using" : usingCode)}

namespace {namespaceName}
{{
	public static partial class {messageGroupName}
	{{
		public static class {internalClassName}
		{{
			{internalClassCode}
		}}
	}}
}}".TrimEmptyLine();

			return code;
		}

		public static string BuildUsingCode(string[] usingNamespaces)
		{
			if (usingNamespaces == null ||
				usingNamespaces.Length == 0)
			{
				return string.Empty;
			}

			var usingCodes = usingNamespaces.Select(usingName => $"using {usingName};");
			var finaleCode = string.Join(Environment.NewLine, usingCodes);

			return finaleCode;
		}

		public static string GenerateParameterTypeNameCode(ParameterInfo[] parameters)
		{
			return parameters.Select(param => $", {TypeUtility.GetFriendlyTypeName(param.ParameterType)} {param.Name}").Join();
		}

		public static string GenerateParameterNameCode(ParameterInfo[] parameters)
		{
			return parameters.Select(param => $", {param.Name}").Join();
		}
	}
}
